------------------------------------------------------------------------------
-- Data population script for table utl.config.
-- WARNING: *** This script overwrites the entire table! ***
--          *** Save important content before running.   ***
-- To run this script from the command line:
--   $ sqlplus utl/[password]@[instance] @config.sql
-- This file was generated from database instance APP01.
--   Database Time    : 06OCT2005 17:23:17
--   IP address       : 10.44.0.228
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : misqux42
--   O/S user         : abc
------------------------------------------------------------------------------
set feedback off;
set scan off;
prompt Populating 102 records into table utl.config.

-- Truncate the table:
truncate table utl.config;

------------------------------------------------------------------------------
-- Populating the table:
------------------------------------------------------------------------------

--{{BEGIN AUTOGENERATED CODE}}

insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      '$JAVA_HOME',
      'Java home',NULL,NULL,NULL,
      '/usr/java1.4/jdk',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      '$APP_HOME',
      'Environment Variable',NULL,NULL,NULL,
      '/app/abc',to_date('20050726171616','YYYYMMDDHH24MISS'),
      'Test'
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'AnalyzeFrequency',
      'Frequency in days between stats gathering',1,NULL,NULL,NULL,to_date('19701101000001','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ArchiveColumnSeparator',
      'Column separator for archives',NULL,NULL,NULL,
      ',',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ArchiveDateFormat',
      'Date format for the display of dates in archives. Format should correspond to Oracle date format specification.',NULL,NULL,NULL,
      '2005/02/15 14:29:16',to_date('20050912161837','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ArchiveEscapeColumnSeparator',
      'Escape char to use when the column separator char is encountered in data',NULL,NULL,NULL,
      '\',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ArchiveFileAge',
      'Archive File Housekeeping: Maximun age in Days before files are deleted.',7,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ArchiveHeadingsOn',
      'Show headings on columns on archives. (No leading or trailing slashes.). Values: 0 or 1',1,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ArchiveHttpPath',
      'Path as seen by the the HTTP server that will hold archives. (No leading or trailing slashes.)',NULL,NULL,NULL,
      'archives',to_date('20050920170943','YYYYMMDDHH24MISS'),
      'fix'
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ArchiveTotalsOn',
      'Show totals row in archive',0,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'DefaultSearchRadius',
      'Search radius in meters for geographical searches when not specified',1000,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'FTPClientDirectory',
      'FTP Absolute Directory on FTP client',NULL,NULL,NULL,
      '/public/migrate',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'FTPFileAge',
      'FTP File Housekeeping: Maximun age in Days before files are deleted.',30,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'FTPPassword',
      'FTP User password (in the clear)',NULL,NULL,NULL,
      'merlin',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'FTPServer',
      'FTP Server name or IP address for uploading and downloading file',NULL,NULL,NULL,
      'a_remote_server',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'FTPServerDirectory',
      'FTP Directory on FTP server, in UNIX format',NULL,NULL,NULL,
      '.',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'FTPUser',
      'FTP User name ',NULL,NULL,NULL,
      'upload',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'GUIDateFormat',
      'Date format used for displaying in the GUI',NULL,NULL,NULL,
      'YYYY/MM/DD',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'GUIDateTime',
      'Time format used for displaying in the GUI',NULL,NULL,NULL,
      'HH24:MI',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'GUIDateTimeFormat',
      'Date/time format used for displaying in the GUI',NULL,NULL,NULL,
      'YYYY/MM/DD HH24:MI:SS',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'GUIMaxRecords',
      'Maximimum number of records to display in GUI-based queries',1000,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'LogDateFormat',
      'Date format for the display of dates in log file. Format should correspond to Oracle date format specification.',NULL,NULL,NULL,
      'YYYY/MM/DD HH24:MI:SS',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'LogFileAge',
      'Log file Housekeeping: Maximun age in Days before LogEvent entries are deleted.',30,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'LogFileDir',
      'Absolute path the log file. Logrotate will manage the file. Remember to change your logrotate configuration if you change this! Also, UTL_FILE needs to be able to write to this directory.',NULL,NULL,NULL,
      'VCRLOG',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'LogFileName',
      'Log filename. Logrotate will manage the file. Remember to change your logrotate configuration if you change this!',NULL,NULL,NULL,
      'events',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'LogLevel',
      'None=0, Basic=1 (default), Verbose=2 or Debug (very verbose)=3 logging of events',3,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'LogTableAge',
      'Log table Housekeeping: Maximun age in MONTHS before entries are deleted.',2,NULL,NULL,NULL,to_date('20050912181249','YYYYMMDDHH24MISS'),
      'hh'
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'LogTargetTypes',
      'Event log target: any combinarion of TABLE or FILE or OUTPUT. Avoid using OUTPUT on production systems.',NULL,NULL,NULL,
      'TABLE FILE',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'LogTypes',
      'The types of messages that are logged: ERROR,EVENT,INFO,DEBUG',NULL,NULL,NULL,
      'ERROR,EVENT,INFO,DEBUG',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'PatchLevel',
      'Patch-level in the form a string',NULL,NULL,NULL,
      'build011',to_date('20050914152451','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'Pi',
      'Value of PI as a floating point number, and also the first 250 digits of Pi in string form',NULL,3.14159265358979,NULL,
      '3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ReportColumnSeparator',
      'Column separator for reports',NULL,NULL,NULL,
      ',',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ReportDateFormat',
      'Date format for the display of dates in reports. Format should correspond to Oracle date format specification.',NULL,NULL,NULL,
      'YYYY/MM/DD HH24:MI:SS',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ReportEscapeColumnSeparator',
      'Escape char to use when the column separator char is encountered in data',NULL,NULL,NULL,
      '\',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ReportFileAge',
      'Report File Housekeeping: Maximun age in Days before files are deleted.',7,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ReportHeadingsOn',
      'Show headings on columns on reports. (No leading or trailing slashes.). Values: 0 or 1',1,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ReportHttpPath',
      'Path as seen by the the HTTP server that will hold reports. (No leading or trailing slashes.)',NULL,NULL,NULL,
      'reports',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'ReportTotalsOn',
      'Show totals row in reports where supported',0,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SQLLDRArchive',
      'Relative Directory off $APP_HOME that processed files will be moved to after loading.',NULL,NULL,NULL,
      'archive',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SQLLDRControl',
      'Relative directory off $APP_HOME that control files are written to',NULL,NULL,NULL,
      'tmp',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SQLLDRData',
      'Relative Directory off $APP_HOME that SQLLDR will load files from, e.g. data. Not leading or trailing slashes!',NULL,NULL,NULL,
      'data',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SQLLDRLog',
      'Relative directory off $APP_HOME that log files are written to',NULL,NULL,NULL,
      'log',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SQLLDRMaxErrors',
      'Maximum number of faulty records tolerated by SQLLDR',0,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SQLLDRMaxWaitTime',
      'Maximum wait time in MINUTES for a complete set of files to be processed ',5,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SQLLDRPassword',
      'Password for SQLLDR User (in the clear)',NULL,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SQLLDRUser',
      'User name for SQLLDR',NULL,NULL,NULL,
      'utl',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerArtificialDate',
      'Override scheduler''s perceived System date if set',NULL,NULL,NULL,NULL,NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerFSMScanDuration',
      'Duration of the last FSM scan in milliseconds',130,NULL,NULL,NULL,to_date('20051006172307','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerFSMScanningInterval',
      'Scheduler FSM scanning interval in seconds',2,NULL,NULL,NULL,to_date('20050617101536','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerHeartbeat',
      'Scheduler FSM Operation indicator',1,NULL,NULL,NULL,to_date('20050606163714','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerLastShutdown',
      'Time that the scheduler was shutdown',NULL,NULL,to_date('20051006142520','YYYYMMDDHH24MISS'),NULL,to_date('20051006142520','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerLastStartup',
      'Last time that the scheduler was started up',NULL,NULL,to_date('20050913152237','YYYYMMDDHH24MISS'),NULL,to_date('20050913152237','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerLogfile',
      'Log file that the scheduler writes to. This value may include environment variables which should also appear in the configuration table. This file should be writable by the Oracle system admin (normally oracle).',NULL,NULL,NULL,
      '$APP_HOME/log/events',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerMaxTasks',
      'The number of execution slots available for executing tasks. This should not be greater than the value of job_queue_processes in the Oracle instance''s init.ora file.',5,NULL,NULL,NULL,NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerRetryInterval',
      'Task retry interval in minutes',1,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerStateChange',
      'Last time that the state of a task was changed',NULL,NULL,to_date('20030222222222','YYYYMMDDHH24MISS'),NULL,to_date('20050912181445','YYYYMMDDHH24MISS'),
      'hh'
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerStatus',
      'Most recent status that the scheduler was known to be in',NULL,NULL,NULL,
      'RUNNING',to_date('20050913152233','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerTaskAbortInterval',
      'Max time to wait for confirmation that a task was successfully aborted (in minutes)',10,NULL,NULL,NULL,NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerTaskEditTimeout',
      'Maximum time in minutes that an edit lock on a task can be held before it is rolled back.',10,NULL,NULL,NULL,NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'SchedulerTempDir',
      'Directory in which the scheduler can store temporary files when makeing external procedure calls. This can be something like ''$APP_HOME/tmp'' if $APP_HOME is defined',NULL,NULL,NULL,
      '$APP_HOME/tmp',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'email.default_sender',
      'If no email sender is defined this one is used',NULL,NULL,NULL,
      'VCR Development',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'email.domain_name',
      'The mail hosts domain',NULL,NULL,NULL,
      'maninvestments.com',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'email.max_attachment_size',
      'max number of bytes that the size of an emailed attachment can be ',5000000,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'email.no_of_retries',
      'number of times pkg_emailer will attempt to get an smtp connection',1,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'email.smtp_server',
      'The mail host that pkg_emailer will use to send emails',NULL,NULL,NULL,
      '192.168.126.225',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'email.smtp_server_port',
      'The mail hosts port',25,NULL,NULL,NULL,to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'exception.tol_level.measure_id',
      'Measure Id for Tolerance Level',5,NULL,NULL,NULL,NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'exception.tol_level.rule_id',
      'Rule Id for Tolerance Level',1,NULL,NULL,NULL,NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'helpdesk.createincidentyn',
      'Whether helpdesk incident should be created or not when an error occurs',NULL,NULL,NULL,
      'Y',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'helpdesk.defaultitem',
      'blah blah',NULL,NULL,NULL,
      'VCR - Development',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'helpdesk.incidentlogger',
      'The NT user who is the "logger" of any automatically created helpdesk incidents',NULL,NULL,NULL,
      'APENNEY',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'helpdesk.sysemailaddress',
      'Email address that should be used to send emails to automatically create an incident in the helpdesk system',NULL,NULL,NULL,
      'apenney@maninvestments.com',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'helpdesk.sysserver',
      'Helpdesk system server - part of body of email used to create incident automatically',NULL,NULL,NULL,
      'misqhd01.maninvestments.ad.man.com',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.adhoc_load_command',
      'shell command to load file(s) to staging area',NULL,NULL,NULL,
      '$APP_HOME/bin/Feed2Oracle --notify',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.bloomberg.firmname',
      'Firmname used for Bloomberg Data Licence account',NULL,NULL,NULL,
      'dl528201',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.bloomberg.poll_attempts',
      'Number of polling attempts for Bloomberg response file',4,NULL,NULL,NULL,NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.bloomberg.poll_interval',
      'Number of seconds between Bloomberg response file polling attempts',15,NULL,NULL,NULL,NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.checker.mand_fields_check_yn',
      'Whether or not mandatory field checks should be performed on incoming data or not',NULL,NULL,NULL,
      'Y',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.checker.max_checks',
      '....',50,NULL,NULL,NULL,to_date('20050303000000','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.checker.type_fields_check_yn',
      'Whether or not type checking should be performed on incoming data or not',NULL,NULL,NULL,
      'N',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.crystal.outputurl',
      'Portion of url used to load reports from website',NULL,NULL,NULL,
      'http://misqprmbidev/Output',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.crystal.visualcutpath',
      'Path used in visual cut batch file',NULL,NULL,NULL,
      '"c:\program files\visual cut\visual cut.exe" -e "c:\vcr\crystal\',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.datapool.classpath',
      'Java classpath to be used for Datapool interface',NULL,NULL,NULL,
      '/app/abc/lib/jtds-1.0.3.jar:/app/vcrdev/lib/DatapoolInterface.jar:/app/vcrdev/lib',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.datapool.jdbcdriver',
      'Class of jdbc driver to be used for Datapool interface',NULL,NULL,NULL,
      'net.sourceforge.jtds.jdbc.Driver',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.datapool.jdbcurl',
      'JDBC URL to be used for Datapool interface',NULL,NULL,NULL,
      'jdbc:jtds:sqlserver://MICHSQL01TEST.maninvestments.ad.man.com:1433/DataPool;user=AppLDN-VCR;password=Lv%APo1',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.moveit.host',
      'MOVEit host server',NULL,NULL,NULL,
      'midatx.com',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.moveit.pass',
      'MOVEit user account password that secure notifications are sent from ',NULL,NULL,NULL,
      'a1s2d3f4',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.moveit.user',
      'MOVEit user account that secure notifications are sent from ',NULL,NULL,NULL,
      'vcr',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.notification.admin_email',
      'email addresses of admin staff',NULL,NULL,NULL,
      'apenney@maninvestments.com',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.notification.error_log_response',
      'email group of admin staff for responses to error log',NULL,NULL,NULL,
      'macdaily@maninvestments.com',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.notification.notify_admin_yn',
      'Whether or not to send notification emails to VCR Admin Staff',NULL,NULL,NULL,
      'Y',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.notification.notify_support_yn',
      'Whether or not to send notification emails to ITO Support Staff',NULL,NULL,NULL,
      'Y',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.notification.std_footer',
      'Standard footer content for VCR notifications',NULL,NULL,NULL,
      'This is an automated email sent by the VCR system. If you do not wish to receive these emails please contact the Helpdesk. Please do not reply to this email.',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.notification.support_email',
      'Email address for ITO Support Staff',NULL,NULL,NULL,
      '_chogben@maninvestments.com, _mildnito1@maninvestments.com',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.proxy.host',
      'Proxy host',NULL,NULL,NULL,
      '192.5.13.196',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.proxy.pass',
      'Proxy password',NULL,NULL,NULL,
      'A1s2d3f4',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.proxy.port',
      'Proxy host port',8080,NULL,NULL,NULL,NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.proxy.user',
      'Proxy user',NULL,NULL,NULL,
      'moveitadmin',NULL,NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.runstatus.COM',
      'Complete',NULL,NULL,NULL,
      'Complete',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
commit;
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.runstatus.ERR',
      'Error',NULL,NULL,NULL,
      'Error',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.runstatus.INP',
      'In Progress',NULL,NULL,NULL,
      'In Progress',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );
insert into utl.config
      (VARIABLE,DESCRIPTION,INT_VALUE,FLOAT_VALUE,DATE_VALUE,STRING_VALUE,TMSTMP,CHANGE_REASON)
values(
      'vcr.runstatus.WAI',
      'Waiting',NULL,NULL,NULL,
      'Waiting',to_date('20050215142916','YYYYMMDDHH24MISS'),NULL
      );

--{{END AUTOGENERATED CODE}}

commit;
set feedback on;
set scan on;
------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

